### ISSUE TITLE
MHA stopped working on Outlook for iOS

### ISSUE THREAD

**Issue by littlebigco-dev** [microsoft/MHA#33]
Hey,

I use the plugin quite extensively. Also on the Outlook for iOS. However, since a couple of days, it stopped working. I always end up with a screen titled "MOBILE DIFFERENTIATION PAGE" and it tells me "YOU SHOULD NOT BE HERE" and "Diagnostics". That's all. I guess the message is right, I shouldn't be there. How can I avoid getting there and get the information it is supposed to show?
It doesn't matter what mail I use the plugin on. The result is always the same. However, on Outlook for Windows, it works as expected for the same emails. I am using Office 365.
Any ideas?

**Comment by stephenegriffin** [comment]
"YOU SHOULD NOT BE HERE" does not exist in the current version of the add-in. That's an old error message which I've since updated. I've also in the meantime updated my caching headers to force reloads.

So - what's going on:
1 - Outlook for iOS put out an update which broke one of the libraries I used.
2 - I coded a workaround and shipped it
3 - Since my old pages had no caching headers, Outlook for iOS isn't looking for the updated pages.

One thing which I know will fix this is to uninstall Outlook for iOS and reinstall. That will force it to download MHA again and get the new files (with proper cache headers so this shouldn't happen again). If anyone finds a less drastic workaround please speak up and thank you!

**Comment by stephenegriffin** [comment]
Also - I think Outlook for iOS' next update will fix the problem which broke MHA in the first place, so you might start working again, but still with the old version of the app...
