### ISSUE TITLE
Error: Unable to obtain callback token.

### ISSUE THREAD

**Issue by stephenegriffin** [microsoft/MHA#52]
Reported in comments for #37 by @luisjmoreno

-------- Outlook for Mac
User Agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko)
Requirement set = 1.5
hostname = Outlook
hostVersion = 16.9 (180116.02)
itemType = message
itemClass = IPM.Note
contentLanguage = en-US
displayLanguage = en-US
touchEnabled = false
ERROR: Unable to obtain callback token.
[object Object]
ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:13
{anonymous}()@https://mha.azurewebsites.net/Scripts/GetHeadersRest.js:21:22
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:165814
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:158350
agaveResponseCallback()@user-script:9:1:9847
agaveHostCallback()@user-script:9:1:5046
agaveHostCallback()@user-script:9:1:2578
{anonymous}()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:60
global code()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:135
ERROR: Unable to obtain callback token.
[object Object]
ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:95:23
{anonymous}()@https://mha.azurewebsites.net/Scripts/GetHeadersRest.js:21:22
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:165814
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:158350
agaveResponseCallback()@user-script:9:1:9847
agaveHostCallback()@user-script:9:1:5046
agaveHostCallback()@user-script:9:1:2578
{anonymous}()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:60
global code()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:135
User Agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko)
Requirement set = 1.5
hostname = Outlook
hostVersion = 16.9 (180116.02)
itemType = message
itemClass = IPM.Note
contentLanguage = en-US
displayLanguage = en-US
touchEnabled = false
ERROR: Unable to obtain callback token.
[object Object]
ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:13
{anonymous}()@https://mha.azurewebsites.net/Scripts/GetHeadersRest.js:21:22
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:165814
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:158350
agaveResponseCallback()@user-script:13:1:9847
agaveHostCallback()@user-script:13:1:5046
agaveHostCallback()@user-script:13:1:2578
{anonymous}()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:60
global code()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:13

**Comment by stephenegriffin** [comment]
@luisjmoreno - I fixed and didn't fix this. We're failing to get a callback token for rest, so I think in that case, falling back to EWS is appropriate. I put that in. But we're also failing to log the error properly [object Object], so I put in some code to expand on that. I'd like to see the new diagnostics in this scenario so I can scope the EWS fallback better. Thanks!

**Comment by luisjmoreno** [comment]
Hi Stephen, 
I've got new feedback. You are getting there. MHA only works on the "UI Classic" and "UI New" views on Outlook for Windows and Mac but NOT on Internet Browsers.

**Although it works for Outlook for Mac now**, 
I added the Diagnostics here for you because I noticed some errors that might help you solve these issues. --

User Agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko)
Requirement set = 1.5
hostname = Outlook
hostVersion = 16.9 (180116.02)
itemType = message
itemClass = IPM.Note
contentLanguage = en-US
displayLanguage = en-US
touchEnabled = false
ERROR: Unable to obtain callback token.
{
  "value": null,
  "status": "failed",
  "error": {
   "name": "AccessRestricted",
    "message": "Internal protocol error: '-2147467259'.",
    "code": 9017
  }
}
ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:13
{anonymous}()@https://mha.azurewebsites.net/Scripts/GetHeadersRest.js:21:22
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:165814
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js:9:158350
agaveResponseCallback()@user-script:7:1:9847
agaveHostCallback()@user-script:7:1:5046
agaveHostCallback()@user-script:7:1:2578
{anonymous}()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:60
global code()@https://mha.azurewebsites.net/pages/default.html?_host_Info=Outlook$Mac$16.02$en-US:1:135 
 

**MHA DOES NOT WORK** for Internet Browsers: IE, Firefox or Chrome. I included the Diagnostics using Firefox.

User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Requirement set = 1.3
hostname = OutlookWebApp
hostVersion = 15.0.1347.5
OWAView = ThreeColumns
itemType = message
itemClass = IPM.Note
contentLanguage = 
displayLanguage = en-US
touchEnabled = undefined
ERROR: EWS callback failed
{
  "value": null,
  "status": "failed",
  "error": {
    "name": 1,
    "message": "The remote server returned an error: (404) Not Found."
  }
}
The remote server returned an error: (404) Not Found.
Parsing error:
Cannot parse given Error object
parse@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:1:1299
fromError/<@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:2:14676
fromError@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:2:14644
LogError@https://mha.azurewebsites.net/Scripts/uiToggle.js:120:9
ShowError@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:5
callbackEWS@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:60:9
sendHeadersRequestEWS/<@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:18:13
makeEwsRequestAsync/i.onreadystatechange@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:5497
$2P_1@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:55509
$m_1/<@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:59912

**Comment by stephenegriffin** [comment]
Thanks for the mac feedback - I used that to tighten up the check and not log an error.

OWA - see [this](https://github.com/stephenegriffin/MHA/issues/51#issuecomment-374591174). I wonder if you're hitting the same thing with TLS?

**Comment by luisjmoreno** [comment]
Hi Stephen, 
I don't have an HA cluster. My scenario is fairly simple, a single front-end Exchange 2013 CAS server and a Back-End Exchange 2013 with rest of the services, and nothing else. MHA used to work on this scenario.  

Any ideas in how to diagnose/troubleshoot this one?

**Comment by stephenegriffin** [comment]
Can you get a fiddler and dm me on Twitter to arrange the file transfer?

**Comment by luisjmoreno** [comment]
Hi Stephen, 
I've been just a bit busy and have not have the time to get the fiddler for you. 
Thank you,

**Comment by stephenegriffin** [comment]
Haven't seen callback token errors since 4/12. Can revisit if issue occurs again

**Comment by rjpruitt16** [comment]
I am currently suffering from the same error. I have a mac as well. Have you found a solution?
